version: "3.8"

services:
  app:
    build: .
    container_name: defi-app
    ports:
      - "8501:8501"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis_server
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
